### ISSUE TITLE
Model mapping do not work for Azure OpenAI

### ISSUE THREAD

**Issue by LukaszFliegel** [microsoft/AICentral#100]
Hello, I noticed an issue when using Azure Open AI Service in my configuration. Looks to me like model mappings are only supported for OpenAI (not Azure OpenAI).

The class OpenAIDownstreamEndpointAdapter in a constructor takes model mappings
https://github.com/microsoft/AICentral/blob/6b0654deeda7103eec1ae2a00cf9d67cdda6f036/src/AICentral/Endpoints/OpenAI/OpenAIDownstreamEndpointAdapter.cs#L15
and passes them to the base class OpenAILikeDownstreamEndpointAdapter. However AzureOpenAIDownstreamEndpointAdapter class does not take it in a constructor and passes new empty dictionary to a base OpenAILikeDownstreamEndpointAdapter.
https://github.com/microsoft/AICentral/blob/6b0654deeda7103eec1ae2a00cf9d67cdda6f036/src/AICentral/Endpoints/AzureOpenAI/AzureOpenAIDownstreamEndpointAdapter.cs#L13

Which mean, when handling request AzureOpenAI services doesn't follow mapping.

**Comment by graemefoster** [comment]
Yeah - do you see value in the mappings? The reason I do it for Open AI is it doesn’t have the notion of deployments, so to send an AOAI request to Open AI requires a map. 

But with Azure Open AI I figured that you can ensure the same deployment exists on all the endpoints. 

It’s pretty easy to add the mapping functionality in. Just wasn’t sure if it was worth it or not.

**Comment by LukaszFliegel** [comment]
If you are asking if I would have seen values in `AzureOpenAIDownstreamEndpointAdapterFactory` when reading configuration then yes. But class AzureOpenAIEndpointPropertiesConfig does not map them. 

I have multiple AOAI's and they have models deployed on the same key (like GPT-4) that represents other version. GPT-4 key in one instance is equivalent to version 1106-Preview and on another instance, the same GPT-4 key is equivalent to 0125-Preview version. I would like to ensure that when using one key I would be routed to the same model. So wanted to add mapping like 

```
"ModelMappings": {
    "gpt-4-newest": "gpt-4",
    "gpt-4-0125": "gpt-4",
    "gpt-4-1106": "gpt-4-1106-Preview"
}
```

**Comment by graemefoster** [comment]
Cool - I’ll add it in tomorrow. Nice to see a use case for this feature.
