### ISSUE TITLE
404 Not found error on start 

### ISSUE THREAD

**Issue by iamp3** [microsoft/AICentral#111]
When we start our service on AKS we got this error:
`
[11:23:39 INF] Configuring Pipeline MyPipeline on Host *
[11:23:39 INF] Configured Pipeline MyPipeline on Host *
[11:23:40 INF] Now listening on: http://[::]:8080
[11:23:40 INF] Application started. Press Ctrl+C to shut down.
[11:23:40 INF] Hosting environment: Development
[11:23:40 INF] Content root path: /app
[11:23:40 INF] Request starting HTTP/1.1 GET http://10.6.20.231:8080/ - null null
[11:23:41 INF] Executing endpoint 'HTTP: Get, Post, Delete {*:rest}'
[11:23:41 INF] Executing Pipeline MyPipeline
[11:23:41 DBG] Detected Other from incoming request
[11:23:41 DBG] Rewritten URL from http://10.6.20.231:8080/ to ${OpenAPI_endpoint}.
[11:23:41 DBG] Making call to ${OpenAPI_endpoint}
[11:23:41 INF] Start processing HTTP request GET ${OpenAPI_endpoint}
[11:23:41 VRB] Request Headers:
Accept: */*
Connection: close
User-Agent: kube-probe/1.28
api-key: SECRET
[11:23:41 INF] Sending HTTP request GET ${OpenAPI_endpoint}
[11:23:41 VRB] Request Headers:
Accept: */*
Connection: close
User-Agent: kube-probe/1.28
[11:23:41 DBG] Called ${OpenAPI_endpoint}. Response Code: NotFound
[11:23:41 DBG] Received Azure Open AI Response. Status Code: NotFound
[11:23:41 DBG] Detected non-chunked encoding response. Sending response back to consumer
[11:23:41 DBG] AICentral took 00:00:00.4091934 to get initial response from AI Service and 00:00:00 to retransmit the response
[11:23:41 INF] Executed Pipeline MyPipeline
[11:23:41 INF] Executed endpoint 'HTTP: Get, Post, Delete {*:rest}'
[11:23:41 INF] Request finished HTTP/1.1 GET http://10.6.20.231:8080/ - 404 null application/json 517.2771ms
[11:23:42 INF] Request starting HTTP/1.1 GET http://10.6.20.231:8080/ - null null
[11:23:42 INF] Request starting HTTP/1.1 GET http://10.6.20.231:8080/ - null null
....
....
[11:23:52 DBG] Called ${OpenAPI_endpoint}. Response Code: NotFound
[11:23:52 DBG] Received Azure Open AI Response. Status Code: NotFound
[11:23:52 DBG] Detected non-chunked encoding response. Sending response back to consumer
[11:23:52 DBG] AICentral took 00:00:00.0551376 to get initial response from AI Service and 00:00:00 to retransmit the response
[11:23:52 INF] Executed Pipeline MyPipeline
[11:23:52 INF] Executed endpoint 'HTTP: Get, Post, Delete {*:rest}'
[11:23:52 INF] Request finished HTTP/1.1 GET http://10.6.20.231:8080/ - 404 null application/json 56.9784ms
`

Configuration file:
```json
{
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft.AspNetCore": "Warning",
      "AICentralApi": "Debug"
    }
  },
  "WEBSITES_PORT": "8080",
  "APPLICATIONINSIGHTS_CONNECTION_STRING": "SECRET",
  "APPINSIGHTS_INSTRUMENTATIONKEY": "SECRET",
  "AllowedHosts": "*",
  "AICentral": {
    "Endpoints": [
      {
        "Type": "AzureOpenAIEndpoint",
        "Name": "openai-1",
        "Properties": {
            "LanguageEndpoint": "${endpoint}",
            "ModelMappings": {
              "Gpt35Turbo0613": "gpt-3.5-turbo",
              "gpt4turbo0125Preview": "gpt_4_turbo",
              "textembeddingada002": "text-embedding-ada-002",
              "textembedding3large": "text-embedding-3-large"
            },
            "EnforceMappedModels": true,
            "AuthenticationType": "ApiKey",
            "ApiKey": "SECRET",
            "MaxConcurrency": 5,
            "AutoPopulateEmptyUserId": true
        }
    }
    ],
    "EndpointSelectors": [
      {
        "Type": "SingleEndpoint",
        "Name": "default",
        "Properties": {
          "Endpoint": "openai-1"
        }
      }
    ],
    "GenericSteps": [
      {
        "Type": "AspNetCoreFixedWindowRateLimiting",
        "Name": "window-rate-limiter",
        "Properties": {
          "LimitType": "PerAICentralEndpoint",
          "MetricType": "Requests",
          "Options": {
            "Window": "00:00:10",
            "PermitLimit": 100
          }
        }
      },
      {
        "Type": "AzureMonitorLogger",
        "Name": "azure-monitor-logger",
        "Properties": {
          "WorkspaceId": "SECRET",
          "Key": "SECRET",
          "LogPrompt": true,
          "LogResponse": false,
          "LogClient": true
        }
      }
    ],
    "AuthProviders": [
      {
        "Type": "AllowAnonymous",
        "Name": "no-auth"
      }
    ],
    "Pipelines": [
      {
        "Name": "MyPipeline",
        "Host": "*",
        "EndpointSelector": "default",
        "AuthProvider": "no-auth"
      }
    ]
  }
}
```

@graemefoster Could you advice what we missed in our configuration?

**Comment by graemefoster** [comment]
Hi @iamp3 - I think it’s the “$(endpoint)” you’ve set as the LanguageEndpoint. This should be your Azure Open AI endpoint. The logs suggest this is resolving to “http://10.6.20.231:8080/“. 

I would expect it to be a url like “https://myazopenai. openai.azure.com”

**Comment by iamp3** [comment]
> Hi @iamp3 - I think it’s the “$(endpoint)” you’ve set as the LanguageEndpoint. This should be your Azure Open AI endpoint. The logs suggest this is resolving to “[http://10.6.20.231:8080/“](http://10.6.20.231:8080/%E2%80%9C).
> 
> I would expect it to be a url like “https://myazopenai. openai.azure.com”

Thanks for answer! 
I masked endpoint value, because I couldnt share domain name. I see in logs that endpoint is correct and Rewritten URL process exist:

`
[11:23:41 DBG] Detected Other from incoming request
[11:23:41 DBG] Rewritten URL from http://10.6.20.231:8080/ to https://$masked_domain_name.openai.azure.com/.
[11:23:41 DBG] Making call to https://$masked_domain_name.openai.azure.com/
[11:23:41 INF] Start processing HTTP request GET https://$masked_domain_name.openai.azure.com/
[11:23:41 VRB] Request Headers:
Accept: */*
Connection: close
User-Agent: kube-probe/1.28
api-key: SECRET

[11:23:41 INF] Sending HTTP request GET https://$masked_domain_name.openai.azure.com/
[11:23:41 VRB] Request Headers:
Accept: */*
Connection: close
User-Agent: kube-probe/1.28
api-key: $SECRET

[11:23:41 INF] Received HTTP response headers after 347.5964ms - 404
`

**Comment by graemefoster** [comment]
Ok cool - you’ve explicitly enabled model mappings. Can you confirm you have deployments with the expected names in your azure open ai service?

for example with this config, if you call ai central with a deployment called “Gpt35Turbo0613” it will rewrite the call to the downstream open ai to a deployment called “gpt-3.5-turbo”.

**Comment by graemefoster** [comment]
Ah ok so a direct curl fails as-well. 
fwiw try posting to 
$AZURE_OPENAI_ENDPOINT/openai/deployments/{deploymentname}/chat/completions?api-version=2024-02-01

you can just pass an empty object as the body. 

The other thing to do is use the azure portals chat playground. You can look at the requests in your browsers dev tools.

**Comment by iamp3** [comment]
> Ok cool @iamp3 - I can see you’ve explicitly enabled model mappings. Can you confirm you have deployments with the expected names in your azure open ai service?
> 
> for example with this config, if you call ai central with a deployment called “Gpt35Turbo0613” it will rewrite the call to the downstream open ai to a deployment called “gpt-3.5-turbo”.

Let me double check, here is my mapping:
```json
            "ModelMappings": {
              "Gpt35Turbo0613": "gpt-3.5-turbo",
              "gpt4turbo0125Preview": "gpt_4_turbo",
              "textembeddingada002": "text-embedding-ada-002",
              "textembedding3large": "text-embedding-3-large"
            },
```           
What I have on portal:
<img width="373" alt="image" src="https://github.com/microsoft/AICentral/assets/38535763/46dc0b5c-4269-4c3b-837c-3a73412e31c3">

**Comment by iamp3** [comment]
> Ah ok so a direct curl fails as-well. fwiw try posting to $AZURE_OPENAI_ENDPOINT/openai/deployments/{deploymentname}/chat/completions?api-version=2024-02-01
> 
> you can just pass an empty object as the body.
> 
> The other thing to do is use the azure portals chat playground. You can look at the requests in your browsers dev tools.

`
curl $AZURE_OPENAI_ENDPOINT/openai/deployments/text_embedding_ada_002/chat/completions?api-version=2024-02-01
{"error":{"code":"404","message": "Resource not found"}}
`

**Comment by graemefoster** [comment]
In the model mappings @iamp3 you need to put the deployment name in the config. Not the model name. 

That’s bad naming on my behalf - when I first wrote this I didn’t get the difference between a model and a deployment. 

So for example,
ModelMappings": {
              "Gpt35Turbo0613": "gpt_35_turbo"
  … 
}

The main use case for this feature was enabling open ai and azure open ai downstream. Open AI doesn’t have the concept of deployments. It only has models. But it’s useful for locking access to a subset of deployments as well.

**Comment by graemefoster** [comment]
For the curl statement:

instead of the embeddings deployment try using 

curl $AZURE_OPENAI_ENDPOINT/openai/deployments/gpt_35_turbo/chat/completions?api-version=2024-02-01

The chat/completions endpoint won’t exist for an embeddings endpoint.

**Comment by iamp3** [comment]
> For the curl statement @iamp3
> 
> instead of the embeddings deployment try using
> 
> curl $AZURE_OPENAI_ENDPOINT/openai/deployments/gpt_35_turbo/chat/completions?api-version=2024-02-01
> 
> The chat/completions endpoint won’t exist for an embeddings endpoint.

Tried completions:

`
curl $AZURE_OPENAI_ENDPOINT/openai/deployments/gpt_35_turbo/chat/completions?api-version=2024-02-01
{"error":{"code":"404","message": "Resource not found"}}
`

**Comment by graemefoster** [comment]
> > For the curl statement @iamp3
> > instead of the embeddings deployment try using
> > curl $AZURE_OPENAI_ENDPOINT/openai/deployments/gpt_35_turbo/chat/completions?api-version=2024-02-01
> > The chat/completions endpoint won’t exist for an embeddings endpoint.
> 
> Tried completions:
> 
> `curl $AZURE_OPENAI_ENDPOINT/openai/deployments/gpt_35_turbo/chat/completions?api-version=2024-02-01 {"error":{"code":"404","message": "Resource not found"}}`

And you did a post?

curl -X POST …

**Comment by iamp3** [comment]
> In the model mappings @iamp3 you need to put the deployment name in the config. Not the model name.
> 
> That’s bad naming on my behalf - when I first wrote this I didn’t get the difference between a model and a deployment. It should really be called DeploymentMappings :(
> 
> So for example, ModelMappings": { "Gpt35Turbo0613": "gpt_35_turbo" … }
> 
> The main use case for this feature was enabling open ai and azure open ai downstream. Open AI doesn’t have the concept of deployments. It only has models. But it’s useful for locking access to a subset of deployments as well.

Tried this as well, but no luck, still got this 404 not found status code. 
```json
                  "ModelMappings": {
                    "Gpt35Turbo0613": "gpt_35_turbo",
                    "gpt4turbo0125Preview": "gpt_4_turbo",
                    "textembeddingada002": "text-embedding-ada-002",
                    "textembedding3large": "text_embedding_3_large"
                  },
```

**Comment by graemefoster** [comment]
Can you try the open ai playground from the portal. Check the urls in your browsers dev tools. Then check the curl statement. Just to confirm that everything is the same.

**Comment by iamp3** [comment]
> > > For the curl statement @iamp3
> > > instead of the embeddings deployment try using
> > > curl $AZURE_OPENAI_ENDPOINT/openai/deployments/gpt_35_turbo/chat/completions?api-version=2024-02-01
> > > The chat/completions endpoint won’t exist for an embeddings endpoint.
> > 
> > 
> > Tried completions:
> > `curl $AZURE_OPENAI_ENDPOINT/openai/deployments/gpt_35_turbo/chat/completions?api-version=2024-02-01 {"error":{"code":"404","message": "Resource not found"}}`
> 
> And you did a post?
> 
> curl -X POST …

Looks like another error, but not found missed

`
curl -X POST $AZURE_OPENAI_ENDPOINT/openai/deployments/gpt_35_turbo/chat/completions?api-version=2024-02-01
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
<HTML><HEAD><TITLE>Length Required</TITLE>
<META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>
<BODY><h2>Length Required</h2>
<hr><p>HTTP Error 411. The request must be chunked or have a content length.</p>
</BODY></HTML>
`

**Comment by graemefoster** [comment]
You’ll need to pass some content to it using 
curl -X POST 
--data “{}”

{} should be enough. Just want to see if you can get something that’s not a 404

**Comment by iamp3** [comment]
> --data “{}” —header “api-key: <key>”

`
curl -X POST $AZURE_OPENAI_ENDPOINT/openai/deployments/gpt_35_turbo/chat/completions?api-version=2024-02-01\
>   -H "Content-Type: application/json" \
>   -H "api-key: $AZURE_OPENAI_API_KEY" \
>   -d "{
>   \"prompt\": \"Once upon a time\",
>   \"max_tokens\": 5
> }"
{
  "error": {
    "message": "'messages' is a required property",
    "type": "invalid_request_error",
    "param": null,
    "code": null
  }
}
`
Get example request from here: https://learn.microsoft.com/en-us/azure/ai-services/openai/reference#example-request

**Comment by graemefoster** [comment]
@iamp3 for that request you linked to, use the /completions endpoint. Not the /chat/completions.

**Comment by iamp3** [comment]
> @iamp3 for that request you linked to, use the /completions endpoint. Not the /chat/completions.

In that case I got this: 
`
{"error":{"code":"OperationNotSupported","message":"The completion operation does not work with the specified model, gpt-35-turbo. Please choose different model and try again. You can learn more about which models can be used with each operation here: https://go.microsoft.com/fwlink/?linkid=2197993."}}
`

**Comment by graemefoster** [comment]
@iamp3 about to head to bed - if the above request works, based on your config file for open ai, you should be able to issue this to ai central:

 curl -X POST $AICENTRAL_ENDPOINT/openai/deployments/Gpt35Turbo0613/completions?api-version=2024-02-01\ -H "Content-Type: application/json" \ -d "{ \"prompt\": \"Once upon a time\", \"max_tokens\": 5 }"

I’ve used the mapped model name that corresponds to the deployment. And you have “no client auth” so I’ve removed the api key.

**Comment by graemefoster** [comment]
> > @iamp3 for that request you linked to, use the /completions endpoint. Not the /chat/completions.
> 
> In that case I got this: `{"error":{"code":"OperationNotSupported","message":"The completion operation does not work with the specified model, gpt-35-turbo. Please choose different model and try again. You can learn more about which models can be used with each operation here: https://go.microsoft.com/fwlink/?linkid=2197993."}}`
> 
> Could we mark it as response from OpenAI API and endpoint reachable?

Ok - yeah this looks good to me. For confirmation you could go back to the /chat/completions endpoint and use this sample:

curl https://YOUR_RESOURCE_NAME.openai.azure.com/openai/deployments/YOUR_DEPLOYMENT_NAME/chat/completions?api-version=2024-02-01 \
  -H "Content-Type: application/json" \
  -H "api-key: YOUR_API_KEY" \
  -d '{"messages":[{"role": "system", "content": "You are a helpful assistant."},{"role": "user", "content": "Does Azure OpenAI support customer managed keys?"},{"role": "assistant", "content": "Yes, customer managed keys are supported by Azure OpenAI."},{"role": "user", "content": "Do other Azure AI services support this too?"}]}'

**Comment by iamp3** [comment]
> @iamp3 about to head to bed - if the above request works, based on your config file for open ai, you should be able to issue this to ai central:
> 
> curl -X POST $AICENTRAL_ENDPOINT/openai/deployments/Gpt35Turbo0613/completions?api-version=2024-02-01\ -H "Content-Type: application/json" \ -d "{ "prompt": "Once upon a time", "max_tokens": 5 }"
> 
> I’ve used the mapped model name that corresponds to the deployment. And you have “no client auth” so I’ve removed the api key.

Our AICENTRAL_POD still failed to start with 404 not found error( Tried to change mapping as you mentioned above, still no luck

**Comment by iamp3** [comment]
> > > @iamp3 for that request you linked to, use the /completions endpoint. Not the /chat/completions.
> > 
> > 
> > In that case I got this: `{"error":{"code":"OperationNotSupported","message":"The completion operation does not work with the specified model, gpt-35-turbo. Please choose different model and try again. You can learn more about which models can be used with each operation here: https://go.microsoft.com/fwlink/?linkid=2197993."}}`
> > Could we mark it as response from OpenAI API and endpoint reachable?
> 
> Ok - yeah this looks good to me. For confirmation you could go back to the /chat/completions endpoint and use this sample:
> 
> curl https://YOUR_RESOURCE_NAME.openai.azure.com/openai/deployments/YOUR_DEPLOYMENT_NAME/chat/completions?api-version=2024-02-01 -H "Content-Type: application/json" -H "api-key: YOUR_API_KEY" -d '{"messages":[{"role": "system", "content": "You are a helpful assistant."},{"role": "user", "content": "Does Azure OpenAI support customer managed keys?"},{"role": "assistant", "content": "Yes, customer managed keys are supported by Azure OpenAI."},{"role": "user", "content": "Do other Azure AI services support this too?"}]}'

This curl request works, thanks

`{"choices":[{"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}},"finish_reason":"stop","index":0,"message":{"content":"Yes, other Azure AI services also support customer managed keys.","role":"assistant"}}],"created":1716820809,"id":"chatcmpl-9TVo9XwoG1UGjPltJKKStlrvhdhDb","model":"gpt-35-turbo","object":"chat.completion","prompt_filter_results":[{"prompt_index":0,"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}}}],"system_fingerprint":null,"usage":{"completion_tokens":12,"prompt_tokens":55,"total_tokens":67}}`

**Comment by graemefoster** [comment]
@iamp3 in the log files can you confirm that the “ Called ${OpenAPI_endpoint}” shows the full url as works with the curl statement?

the log file you pasted says “ https://$masked_domain_name.openai.azure.com”
But shows no path on the url. 

That looks weird to me. I’d expect to see the full path with “/openai/deployments”…

**Comment by iamp3** [comment]
> @iamp3 in the log files can you confirm that the “ Called ${OpenAPI_endpoint}” shows the full url as works with the curl statement?
> 
> the log file you pasted says “ https://$masked_domain_name.openai.azure.com” But shows no path on the url.
> 
> That looks weird to me. I’d expect to see the full path with “/openai/deployments”…
> 
> is there any path rewriting happening before the requests hits the pod?
> 
> I’ll try run it tomorrow in aks if there’s nothing you can think of that might be snipping the path.

We have only 1 place where we define url to our endpoint:
```json
  "AICentral": {
    "Endpoints": [
      {
        "Type": "AzureOpenAIEndpoint",
        "Name": "openai-1",
        "Properties": {
            "LanguageEndpoint": "https://$masked_domain_name.dev.hgenai.gl/",
            "ModelMappings": {
              "Gpt35Turbo0613": "gpt-3.5-turbo",
              "gpt4turbo0125Preview": "gpt_4_turbo",
              "textembeddingada002": "text-embedding-ada-002",
              "textembedding3large": "text-embedding-3-large"
            },
```            

In logs I see this:
```[14:23:22 INF] Now listening on: http://[::]:8080
[14:23:22 INF] Application started. Press Ctrl+C to shut down.
[14:23:22 INF] Hosting environment: Development
[14:23:22 INF] Content root path: /app
[14:23:22 INF] Request starting HTTP/1.1 GET http://10.6.18.11:8080/ - null null
[14:23:22 INF] Executing endpoint 'HTTP: Get, Post, Delete {*:rest}'
[14:23:22 INF] Executing Pipeline MyPipeline
[14:23:22 DBG] Detected Other from incoming request
[14:23:22 DBG] Rewritten URL from http://10.6.18.11:8080/ to https://${OpenAPI_endpoint}.openai.azure.com/.
[14:23:23 DBG] Making call to https://${OpenAPI_endpoint}.openai.azure.com/
[14:23:23 INF] Start processing HTTP request GET https://${OpenAPI_endpoint}.openai.azure.com/
[14:23:23 VRB] Request Headers:
Accept: */*
Connection: close
User-Agent: kube-probe/1.28
api-key: $SECRET

[14:23:23 INF] Sending HTTP request GET https://${OpenAPI_endpoint}.openai.azure.com/
[14:23:23 VRB] Request Headers:
Accept: */*
Connection: close
User-Agent: kube-probe/1.28
api-key: SECRET

[14:23:23 INF] Request starting HTTP/1.1 GET http://10.6.18.11:8080/ - null null
[14:23:23 INF] Executing endpoint 'HTTP: Get, Post, Delete {*:rest}'
[14:23:23 INF] Executing Pipeline MyPipeline
[14:23:23 DBG] Detected Other from incoming request
[14:23:24 DBG] Rewritten URL from http://10.6.18.11:8080/ to https://${OpenAPI_endpoint}.openai.azure.com/.
[14:23:24 DBG] Making call to https://${OpenAPI_endpoint}.openai.azure.com/
[14:23:24 INF] Start processing HTTP request GET https://${OpenAPI_endpoint}.openai.azure.com/```

**Comment by graemefoster** [comment]
@iamp3 - it’d be great if you could share how you expose the ai central service. Is it being consumed directly from inside aks by another pod, exposed by Nginx or another ingress, etc. 

Thanks.

**Comment by graemefoster** [comment]
@iamp3 

just to clarify the flow 

Consumer outside aks -> nginx ingress -> ai-central -> azure open ai

is that the flow you’re trying to get working?

**Comment by graemefoster** [comment]
Hold on… why is a GET request being sent? All requests to AICentral should be the same as those to Azure Open AI which are predominantly POST requests. 

the logging of a GET request suggests something is wrong with the request being sent to ai central. 

Can you try and send the same curl statement (the one that worked, but without the api key) directly to AI Central?

**Comment by graemefoster** [comment]
Random thought - is the request coming from a real consumer or is a service checking the api is up? Maybe it’s a kubernetes health check to make sure the pod is ready?

**Comment by iamp3** [comment]
> @iamp3
> 
> just to clarify the flow
> 
> Consumer outside aks -> nginx ingress -> ai-central -> azure open ai
> 
> is that the flow you’re trying to get working?

Yeap, smth like this

**Comment by iamp3** [comment]
> Random thought - is the request coming from a real consumer or is a service checking the api is up? Maybe it’s a kubernetes health check to make sure the pod is ready?

Yeap, that what we remove from deployment side and looks like pod running now. I`ll check the direct request to aicentral domain

**Comment by iamp3** [comment]
> Random thought - is the request coming from a real consumer or is a service checking the api is up? Maybe it’s a kubernetes health check to make sure the pod is ready?
> 
> I have a feeling this might be it… AI Central definitely should not be proxying a request like this to azure open ai.
> 
> Would love to know if the curl that worked directly to azure open ai works via ai central.

`curl -X POST $AICENTRAL_ENDPOINT/openai/deployments/gpt_35_turbo/chat/completions?api-version=2024-02-01 \
-H "Content-Type: application/json" \
-H "api-key: $AZURE_OPENAI_API_KEY" \
-d '{"messages":[{"role": "system", "content": "You are a helpful assistant."},{"role": "user", "content": "Does Azure OpenAI support customer managed keys?"},{"role": "assistant", "content": "Yes, customer managed keys are supported by Azure OpenAI."},{"role": "user", "content": "Do other Azure AI services support this too?"}]}'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   361    0    35  100   326     50    473 --:--:-- --:--:-- --:--:--   527{"message":"Unknown model mapping"}`

```json
            "ModelMappings": {
              "Gpt35Turbo0613": "gpt-3.5-turbo",
              "gpt4turbo0125Preview": "gpt_4_turbo",
              "textembeddingada002": "text-embedding-ada-002",
              "textembedding3large": "text-embedding-3-large"
            },
```

**Comment by graemefoster** [comment]
What’s in the logs now?

**Comment by graemefoster** [comment]
Ok I’ll have a look tomorrow to see if there’s any issues with Model Mappings. 

Good to know you’re moving with EnforceMappedModels: false

pls share the log of the failed request if possible where the mapped model didn’t work. That’ll help me diagnose why it failed. 

Thanks,
Graeme

**Comment by iamp3** [comment]
> Ok @iamp3 I’ll have a look tomorrow to see if there’s any issues with Model Mappings.
> 
> Good to know you’re moving with EnforceMappedModels: false
> 
> pls share the log of the failed request if possible where the mapped model didn’t work. That’ll help me diagnose why it failed.
> 
> Thanks, Graeme

Thank you! 

Here is the log with unknown mapping:
`[15:37:33 INF] Configuring Endpoint openai-1
[15:37:33 INF] Configuring Endpoint Selector default
[15:37:33 INF] Configuring AuthProviders no-auth
[15:37:33 INF] Configuring AuthProviders window-rate-limiter
[15:37:33 INF] Configuring AuthProviders azure-monitor-logger
[15:37:33 INF] Configuring Pipeline MyPipeline on Host *
[15:37:33 INF] Configured Pipeline MyPipeline on Host *
[15:37:33 INF] Now listening on: http://[::]:8080
[15:37:33 INF] Application started. Press Ctrl+C to shut down.
[15:37:33 INF] Hosting environment: Development
[15:37:33 INF] Content root path: /app
[15:41:41 INF] Request starting HTTP/1.1 POST http://AICENTRAL_DOMAIN/openai/deployments/gpt_35_turbo/chat/completions?api-version=2024-02-01 - application/json 326
[15:41:41 INF] Executing endpoint 'HTTP: Post /openai/deployments/{deploymentName}/chat/completions'
[15:41:41 INF] Executing Pipeline MyPipeline
[15:41:41 DBG] Detected Chat from incoming request
[15:41:41 INF] Executed Pipeline MyPipeline
[15:41:41 INF] Setting HTTP status code 404.
[15:41:41 INF] Writing value of type '<>f__AnonymousType0`1' as Json.
[15:41:41 INF] Executed endpoint 'HTTP: Post /openai/deployments/{deploymentName}/chat/completions'
[15:41:41 INF] Request finished HTTP/1.1 POST http://AICENTRAL_DOMAIN/openai/deployments/gpt_35_turbo/chat/completions?api-version=2024-02-01 - 404 null application/json; charset=utf-8 106.4374ms`

**Comment by graemefoster** [comment]
Also will check out the Model Mappings to see if there are any issues there.

**Comment by graemefoster** [comment]
> > Ok @iamp3 I’ll have a look tomorrow to see if there’s any issues with Model Mappings.
> > Good to know you’re moving with EnforceMappedModels: false
> > pls share the log of the failed request if possible where the mapped model didn’t work. That’ll help me diagnose why it failed.
> > Thanks, Graeme
> 
> Thank you!
> 
> Here is the log with unknown mapping: `[15:37:33 INF] Configuring Endpoint openai-1 [15:37:33 INF] Configuring Endpoint Selector default [15:37:33 INF] Configuring AuthProviders no-auth [15:37:33 INF] Configuring AuthProviders window-rate-limiter [15:37:33 INF] Configuring AuthProviders azure-monitor-logger [15:37:33 INF] Configuring Pipeline MyPipeline on Host * [15:37:33 INF] Configured Pipeline MyPipeline on Host * [15:37:33 INF] Now listening on: http://[::]:8080 [15:37:33 INF] Application started. Press Ctrl+C to shut down. [15:37:33 INF] Hosting environment: Development [15:37:33 INF] Content root path: /app [15:41:41 INF] Request starting HTTP/1.1 POST http://AICENTRAL_DOMAIN/openai/deployments/gpt_35_turbo/chat/completions?api-version=2024-02-01 - application/json 326 [15:41:41 INF] Executing endpoint 'HTTP: Post /openai/deployments/{deploymentName}/chat/completions' [15:41:41 INF] Executing Pipeline MyPipeline [15:41:41 DBG] Detected Chat from incoming request [15:41:41 INF] Executed Pipeline MyPipeline [15:41:41 INF] Setting HTTP status code 404. [15:41:41 INF] Writing value of type '<>f__AnonymousType01' as Json. [15:41:41 INF] Executed endpoint 'HTTP: Post /openai/deployments/{deploymentName}/chat/completions' [15:41:41 INF] Request finished HTTP/1.1 POST http://AICENTRAL_DOMAIN/openai/deployments/gpt_35_turbo/chat/completions?api-version=2024-02-01 - 404 null application/json; charset=utf-8 106.4374ms`

Hi @iamp3 - this log shows you curl'd to **http://AICENTRAL_DOMAIN/openai/deployments/gpt_35_turbo/chat/completions** In the config with Enforced Model Mappings, your dictionary doesn't advertise 'gpt_35_turbo' as an incoming model name. This is why it didn't work.

Bigger explanation: your model mappings are defined as 
            "ModelMappings": {
              "Gpt35Turbo0613": "gpt-3.5-turbo",
              "gpt4turbo0125Preview": "gpt_4_turbo",
              "textembeddingada002": "text-embedding-ada-002",
              "textembedding3large": "text-embedding-3-large"
            },

If you want your curl command to trigger a mapped model, then you need to curl to a key in this dictionary. Not a value.
For example,

curl http://AICENTRAL_DOMAIN/openai/deployments/gpt_35_turbo/chat/completions will **NOT** work with Enforced models.

curl http://AICENTRAL_DOMAIN/openai/deployments/Gpt35Turbo0613/chat/completions **will** work with Enforced models, and will rewrite the request to 'openai/deployments/**gpt_35_turbo**/chat/completions when it proxies it.

Hope this helps. 
Graeme
