### ISSUE TITLE
Rate limits issue 

### ISSUE THREAD

**Issue by iamp3** [microsoft/AICentral#115]
Hi @graemefoster

We faced an issue with rate-limits in our requests. Looks like after 1 min we got 499 status code on aicentral, do we have any rate-limits on aicentral? 
If I made the same request directly to Private Endpoint via curl, it takes 2 min 40 sec, but I got response. 

Sometime it works less than <1 min and no problem for aicentral app for such requests, but If we have a quite big load or heavy requests this >1 min limit issue appears.

Tested on this curl request while big load on OpenAI instances exist:
`curl --location 'https://$PRIVATE_ENDPOINT.openai.azure.com/openai/deployments/gpt_4_turbo/chat/completions?api-version=2024-02-01' \
--header 'api-key: $SECRET' \
--header 'Content-Type: application/json' \
--data '{
   "messages": [
   {
      "role": "user",
      "content": "in 1000 words, make your response as long as possible, whats the best thing about London?"
    }
  ]
}'`

**Comment by graemefoster** [comment]
Hi @iamp3 AICentral has a few approaches to rate-limiting. If you can share your logfile, and your config, it'd be easy to work out what's happening.

The process is as-follows:

1: Has a user configured AI Central rate-limiting in config? If so, check this and return 429 if AI Central thinks it is necessary
2: Try a downstream server. 
   a: if that server previously returned a 429 then don't bother trying it until the time it indicated when it returned its 429
   b: Move to the next server in the pool and repeat
3: If we run out of options in the pool, and the last response was 429, then return that to the consumer.

The logs and config are definitely the best things to diagnose.

**Comment by iamp3** [comment]
> Hi @iamp3 AICentral has a few approaches to rate-limiting. If you can share your logfile, and your config, it'd be easy to work out what's happening.
> 
> The process is as-follows:
> 
> 1: Has a user configured AI Central rate-limiting in config? If so, check this and return 429 if AI Central thinks it is necessary 2: Try a downstream server. a: if that server previously returned a 429 then don't bother trying it until the time it indicated when it returned its 429 b: Move to the next server in the pool and repeat 3: If we run out of options in the pool, and the last response was 429, then return that to the consumer.
> 
> The logs and config are definitely the best things to diagnose - but if there's only a single downstream, or all downstreams are returning 429's, then AI Central will hit the end of its options and return 429 to the caller.

Hi @graemefoster
I may have misidentified the rate-limits, as I see an error of 499 in the logs, not 429. Here is an example of a recent log:

`[15:42:05 DBG] Detected Chat from incoming request
[15:42:05 DBG] Lowest Latency selector is handling request
[15:42:05 DBG] Rewritten URL from http://$public_domain/openai/deployments/gpt_4_turbo/chat/completions?api-version=2024-02-01 to https://$PRIVATE_ENDPOINT/openai/deployments/gpt_4_turbo/chat/completions?api-version=2024-02-01.
[15:42:05 DBG] Making call to https://$PRIVATE_ENDPOINT/openai/deployments/gpt_4_turbo/chat/completions?api-version=2024-02-01
[15:42:05 INF] Start processing HTTP request POST https://$PRIVATE_ENDPOINT/openai/deployments/gpt_4_turbo/chat/completions?api-version=2024-02-01
[15:42:05 VRB] Request Headers:
Accept: */*
User-Agent: PostmanRuntime/7.36.3
Accept-Encoding: gzip, deflate, br
X-Request-ID: $REQ_ID
X-Real-IP: $IP
X-Forwarded-For: $IP
X-Forwarded-Host: $public_domain
X-Forwarded-Port: 443
X-Forwarded-Proto: https
X-Forwarded-Scheme: https
X-Scheme: https
Postman-Token: $SECRET
api-key: $SECRET
Content-Type: application/json; charset=utf-8

[15:42:05 INF] Sending HTTP request POST https://$PRIVATE_ENDPOINT/openai/deployments/gpt_4_turbo/chat/completions?api-version=2024-02-01
[15:42:05 VRB] Request Headers:
Accept: */*
User-Agent: PostmanRuntime/7.36.3
Accept-Encoding: gzip, deflate, br
X-Request-ID: $REQ_ID
X-Real-IP: $IP
X-Forwarded-For: $IP
X-Forwarded-Host: $public_domain
X-Forwarded-Port: 443
X-Forwarded-Proto: https
X-Forwarded-Scheme: https
X-Scheme: https
Postman-Token: $SECRET
api-key: $SECRET
Content-Type: application/json; charset=utf-8

[15:43:05 INF] Executed endpoint 'HTTP: Post /openai/deployments/{deploymentName}/chat/completions'
[15:43:05 INF] Request finished HTTP/1.1 POST http://$public_domain/openai/deployments/gpt_4_turbo/chat/completions?api-version=2024-02-01 - 499 null null 60004.7792m`

I thought it was something at the level of our nginx-ingress and added a couple of annotations to our ingress configuration:
`nginx.org/proxy-connect-timeout=9999s
nginx.org/proxy-read-timeout=9999s`

but that didn't work either and we get 499 right after 1 minute of waiting for an answer.

**Comment by graemefoster** [comment]
Hi @iamp3, my apologies - I thought you had a typo and meant 429.

The 499 occurs exactly 60 seconds after your request starts. It looks like whatever is calling AI Central has a Client Timeout set to 60 seconds. Can you share how are you calling it?

**Comment by iamp3** [comment]
> Hi @iamp3, my apologies - I thought you had a typo and meant 429.
> 
> The 499 occurs exactly 60 seconds after your request starts. It looks like whatever is calling AI Central has a Client Timeout set to 60 seconds. Can you share how are you calling it?

Sure, I called via Postman/Curl, for example:

`curl --location 'https://$PRIVATE_ENDPOINT.openai.azure.com/openai/deployments/gpt_4_turbo/chat/completions?api-version=2024-02-01' \ --header 'api-key: $SECRET' \ --header 'Content-Type: application/json' \ --data '{ "messages": [ { "role": "user", "content": "in 1000 words, make your response as long as possible, whats the best thing about London?" } ] }'`

But it happens only for heavy load requests or when we have a lot requests to OpenAI at all for simple request

**Comment by graemefoster** [comment]
OK - there's a good chance this is nginx terminating the connection due to nothing being returned from AOAI. The heavy load requests suggests that AOAI is doing some kind of internal throttling on your requests, so some are slower than others.

Are your nginx ingress annotations correct? According to this (https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/) they should be:

``` nginx.ingress.kubernetes.io/proxy-send-timeout ``` and
``` nginx.ingress.kubernetes.io/proxy-connect-timeout ```

not ``` nginx.org/proxy-read-timeout ```

(```proxy-send-timeout``` is the one I'd expect needs increasing).

**Comment by graemefoster** [comment]
AI Central does have a timeout on receiving a request from AOAI but it's purposefully set quite high (possibly too high!)
![image](https://github.com/microsoft/AICentral/assets/160201/9a357db6-1568-4e02-b55c-50a21f74daf7)

**Comment by iamp3** [comment]
> AI Central does have a timeout on receiving a request from AOAI but it's purposefully set quite high (possibly too high!) ![image](https://private-user-images.githubusercontent.com/160201/336371658-9a357db6-1568-4e02-b55c-50a21f74daf7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0OTA0NDEsIm5iZiI6MTcxNzQ5MDE0MSwicGF0aCI6Ii8xNjAyMDEvMzM2MzcxNjU4LTlhMzU3ZGI2LTE1NjgtNGUwMi1iNTVjLTUwYTIxZjc0ZGFmNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNFQwODM1NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jN2YxMmE3ZGVjMmY2NjBhM2YwM2NkYjM3NDdmYzBiNDg5M2MzZDNhYzQxMzgxNjIxZjQ1NDVhZmNhY2ExNGVhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.j4YqEPNADbP3F6XPmH-giPU1UNt9qYv5FQk7oTbbwrQ)

Thanks @graemefoster, mb I was refer to wrong doc: https://docs.nginx.com/nginx-ingress-controller/configuration/ingress-resources/advanced-configuration-with-annotations/
I`ll check ur link and try it out.

**Comment by graemefoster** [comment]
Interesting - there's the "nginx ingress controller" published by nginx, and also an ingress-nginx published by Google.
Which one are you using?!

https://docs.nginx.com/nginx-ingress-controller/
https://kubernetes.github.io/ingress-nginx/

**Comment by iamp3** [comment]
> @iamp3 there's a good chance this is nginx terminating the connection due to nothing being returned from AOAI. The heavy load requests suggests that AOAI is doing some kind of internal throttling on your requests, so some are slower than others.
> 
> Are your nginx ingress annotations correct? According to this (https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/) they should be:
> 
> `nginx.ingress.kubernetes.io/proxy-read-timeout` and `nginx.ingress.kubernetes.io/proxy-connect-timeout`
> 
> not `nginx.org/proxy-read-timeout`
> 
> (`proxy-read-timeout` is the one I'd expect needs increasing).

It helps, as soon as I put the correct annotations (nginx.ingress.kubernetes.io/proxy-read-timeout and
nginx.ingress.kubernetes.io/proxy-connect-timeout), our requests longer than 1 minute began to pass through aicentral. Thanks @graemefoster
