### ISSUE TITLE
Base64 encoded embedding values cannot be deserialized with latest Azure.AI.OpenAI client

### ISSUE THREAD

**Issue by alexmg** [microsoft/AICentral#149]
## Problem Summary

The latest OpenAI SDK is configured to always return embeddings compressed in a Base64 array values as mentioned in the comment below.

> Currently OpenAI SDK sets embeddings results to be always compressed in Base64 array of values, attempting to use it with non compressed results will give the provided error.

https://github.com/microsoft/semantic-kernel/issues/8833#issuecomment-2447043537

As noted in the thread above, the request now always sets the `EncodingFormat` to `base64` resulting in the response containing the embeddings in the compressed Base64 format.

https://github.com/openai/openai-dotnet/blob/main/src/Custom/Embeddings/EmbeddingClient.cs#L215

In the `JsonResponseHandler` the response is deserialized into a `JsonDocument` so that the appropriate values can be extracted and a `IResponseTransformer` can be applied if provided. The parsed `JsonDocument` contains the correct value in the `embeddings` property at this point with the `+` and `/` characters in place.

When the `JsonDocument` is written to the response stream using the `Utf8JsonWriter` the `string` value in the `embedding` property is encoded and the `+` characters are replaced with `\u002B`. This results in the deserialization code in the client library failing to extract the values from the now modified `embeddings` property.

https://github.com/openai/openai-dotnet/blob/main/src/Custom/Embeddings/OpenAIEmbedding.cs#L108

## Possible Solutions

Set the `Encoder` to  `JavaScriptEncoder.UnsafeRelaxedJsonEscaping` on the `JsonWriterOptions` passed to the `Utf8JsonWriter`. This leaves the contents of the string intact and allows the values to be deserialized correctly in the client library. It requires minimal changes, but the response still undergoes a transformation that could result in other issues surfacing in the future.

```csharp
var jsonWriterOptions = new JsonWriterOptions
{
    Indented = false,
    Encoder = JavaScriptEncoder.UnsafeRelaxedJsonEscaping
};
```

Another solution would be to only serialize and return the `JsonDocument` in the outbound response when modifications are required, and in all other cases return the raw data from the inbound stream instead. It looks like modifications are only necessary when the `AdaptJsonToAzureAISearchTransformer` is used by the `ProxyContext` in the AzureAISearchVectorizer project.

This would require reading the inbound stream contents into something like a `MemoryStream` that can be reused to first deserialize into the `JsonDocument` and then again when being returned to the outbound response stream. In the case that a transformation is required it may be worth still applying the `JavaScriptEncoder.UnsafeRelaxedJsonEscaping` for encoding to reduce the change of differences between the input and output JSON payloads.

```csharp
using var memoryStream = new MemoryStream();
await openAiResponse.Content.CopyToAsync(memoryStream, cancellationToken);

memoryStream.Seek(0, SeekOrigin.Begin);
var response = await JsonDocument.ParseAsync(
    memoryStream,
    cancellationToken: cancellationToken);

context.Response.StatusCode = (int)openAiResponse.StatusCode;
context.Response.SetHeader(HeaderNames.ContentType, "application/json");

if (_adapter is not null
    && _adapter is not EmptyResponseTransformer
    && openAiResponse.IsSuccessStatusCode)
{
    var responseToReturn = _adapter.Transform(response);
    var jsonWriterOptions = new JsonWriterOptions
    {
        Indented = false,
        Encoder = JavaScriptEncoder.UnsafeRelaxedJsonEscaping
    };
    await using var utf8Writer = new Utf8JsonWriter(context.Response.Body, jsonWriterOptions);
    responseToReturn.WriteTo(utf8Writer);
    await utf8Writer.FlushAsync(cancellationToken);
}
else
{
    memoryStream.Seek(0, SeekOrigin.Begin);
    await memoryStream.CopyToAsync(context.Response.Body, cancellationToken);
}
```

There is also a possibility that the AzureAISearchVectorizer implementation will be impacted by this issue (now or in the future) but have not tested this scenario to confirm.

I would be happy to put together a PR with either fix but wanted to raise the issue for your consideration first in case you had preference for a particular direction or have other ideas on how to address the issue.

Thanks for your work on this amazing project @graemefoster and for sharing it with the community!

**Comment by graemefoster** [comment]
Thanks for this @alexmg that's a brilliant write-up. Based on this I had re-created the bug but never would've found the fix. 

I've gone for the simple approach of using the JavaScriptEncoder.UnsafeRelaxedJsonEscaping.
Thanks for the offer of a PR... I realised when I'd added the broken test that the fix was just that tiny addition, so have merged in.

Cheers,
Graeme

**Comment by alexmg** [comment]
No problem. Glad I was able to contribute in some way.

Thanks for getting the fix done so quickly. Your turnaround time on this was incredible. 🚀

I'll take 0.20.6 for spin but already have complete confidence it will work. 👍

**Comment by alexmg** [comment]
As expected, the embedding requests are working in the latest release. Thanks for getting the fix and release out so quickly @graemefoster.

**Comment by graemefoster** [comment]
[like]  Graeme Foster reacted to your message:
________________________________
