### ISSUE TITLE
Support messages from Semantic Kernel

### ISSUE THREAD

**Issue by LukaszFliegel** [microsoft/AICentral#93]
When tried to use AICentral with client that implements [Semantic Kernel](https://github.com/microsoft/semantic-kernel) I received an error. When client doesn't use Semantic Kernel all is fine. Issue is in [AzureOpenAIDetector.cs#42](https://github.com/microsoft/AICentral/blob/main/src/AICentral/AzureOpenAIDetector.cs#L42) where messages suppose to have content property. However message from Semantic Kernel looks different.

Here is the same prompt from an app that uses just Azure.OpenAi nuget:
`[{"content":"Assistant is a large language model.","role":"system"},{"content":"tell me a joke","role":"user"}]`

and here is the same prompt from an app that uses Semantic Kernel:
`[{"content":"Assistant is a large language model.","role":"system"},{"content":[{"text":"tell me a joke","type":"text"}],"role":"user"}]`

Looks like there missing support for message as array with type. Here is the code that does the trick:
```
private static string ExtractPromptText(JsonDocument requestContent)
{
    return string.Join('\n', requestContent.RootElement.GetProperty("messages").EnumerateArray().Select(x =>
    {
        var contentElement = x.GetProperty("content");
        if (contentElement.ValueKind == JsonValueKind.String)
        {
            return contentElement.GetString();
        }
        else if (contentElement.ValueKind == JsonValueKind.Array)
        {
            return string.Join("\n", contentElement.EnumerateArray().Select(y => y.GetProperty("text").GetString()));
        }
        return string.Empty;
    }));
}
```

This method shall be called in [AzureOpenAIDetector.cs#42](https://github.com/microsoft/AICentral/blob/main/src/AICentral/AzureOpenAIDetector.cs#L42). 
I couldn't create a PR since git told me I do not have permissions.

**Comment by graemefoster** [comment]
Thanks @LukaszFliegel - first issue which is awesome. I’ll have a look at this today and ensure we have sem kernel compat.

**Comment by graemefoster** [comment]
Thanks @LukaszFliegel this is fixed now by #94 
https://github.com/microsoft/AICentral/pull/94/files#diff-054dc24196efe772626b404cc0f17f1e6b3f50f44f6d8d254285659061fc516cR52

**Comment by graemefoster** [comment]
@LukaszFliegel - thanks for the PR offer - I think you need to fork and create the PR from your own repo back into this one.

**Comment by LukaszFliegel** [comment]
Thank you so much!
