### ISSUE TITLE
Support messages from Semantic Kernel for embeddings

### ISSUE THREAD

**Issue by LukaszFliegel** [microsoft/AICentral#96]
I see the same issue that was reported in #93. However now it is related to embeddings.
In https://github.com/microsoft/AICentral/blob/main/src/AICentral/AzureOpenAIDetector.cs#L103 the property "input" can be an array like `["Lukasz"]`. It throws the same error as it did for chat completions, that was fixed in https://github.com/microsoft/AICentral/pull/94.

**Comment by graemefoster** [comment]
Thanks again @LukaszFliegel  - will fix this one tomorrow.

**Comment by graemefoster** [comment]
@LukaszFliegel fixed this one (and added a test). Thanks for the bug report.

**Comment by LukaszFliegel** [comment]
Thank you!
